bug fixes and small improvements

diff --git a/files/scripts/hubinstall b/files/scripts/hubinstall
--- a/files/scripts/hubinstall
+++ b/files/scripts/hubinstall
@@ -50,17 +50,23 @@ function installFromGithub() {
 
   mkdir -p ${install_to}
 
-  url=$(curl -sL https://api.github.com/repos/${project}/releases/latest | jq -r ".assets[] | select(.name | test(\"${os}.*${arch}\")) | .browser_download_url")
+  url=$(curl -sL https://api.github.com/repos/${project}/releases/latest | jq -r ".assets[]? | select(.name | test(\"${os}.*${arch}\")) | .browser_download_url?")
+  if [ -z "${url}" ]; then
+    echo 'Error: no releases found, note that pre-releases are not supported!'
+    exit 1
+  fi
   artifact=$(basename ${url})
 
   re='^(.*)\.(tar\.gz|tgz)$'
   if [[ ${artifact} =~ $re ]]; then
     artifact_name=${BASH_REMATCH[1]}
     artifact_ext=${BASH_REMATCH[2]}
-    echo "${artifact_name} is a tarball (${artifact_ext})"
+    if [[ "${DEBUG}" == "true" ]]; then
+      echo "Artifact ${artifact_name} is a tarball (${artifact_ext})"
+    fi
     curl -sLo ${artifact} ${url}
     tar -xzf ${artifact} --one-top-level=${artifact_name} # gnu-tar is needed for this one
-    mv $(find ./${artifact_name} -type f -name ${name}*) ${name}
+    mv $(find ./${artifact_name}/ -type f -name "${name}*") ${name}
     rm ${artifact}
     rm -rf ${artifact_name}
   else
