cleanup

diff --git a/files/scripts/ppa-cleanup b/files/scripts/ppa-cleanup
--- a/files/scripts/ppa-cleanup
+++ b/files/scripts/ppa-cleanup
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+if ! [ -x "$(command -v apt)" ]; then
+  echo "apt command not found"
+  exit 1
+fi
+
 # Remove broken repos
 sudo rm -f /tmp/update.txt; tput setaf 6; echo "Initializing.. Please Wait"
 sudo apt-get update >> /tmp/update.txt 2>&1; awk '( /E:|W:/ && /launchpad/ && /404/ ) { print substr($5,26) }' /tmp/update.txt > /tmp/awk.txt; awk -F '/' '{ print $1"/"$2 }' /tmp/awk.txt > /tmp/awk1.txt; sort -u /tmp/awk1.txt > /tmp/awk2.txt
